theme: jekyll-theme-minimal
title: Gamedev Slides
description: slides presented at a talk to student game developers
show_downloads: true
logo: /images/icons/cat/catglasses.svg
copyright: Technicat LLC
